# 데이터 전처리

- 데이터 형식에 대한 처리
    - 공백 문자
        - str.strip() : 양쪽 공백 제거
        - str.lstrip() : 왼쪽 공백 제거
        - str.rstip() : 오른쪽 공백 제거
        - str.replace() : 공백 전체 제거 또는 대체
    - 데이터 타입
    - 불규칙한 대소문자
    - 불규칙한 구분기호
    - 유효하지 않은 문자
    - 불규칙한 날짜 및 시간 표기

In [1]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

#### 1. 날짜 형식

In [2]:
# 날짜 데이터1 : str 타입
# 날짜 형식 : 2019.01.01   2017-08-13    2017/06/07
str_date = ['2019.01.01', '2017-08-13', '2017/06/07']

In [3]:
# Series 의 values로 저장
pd.Series(str_date)

0    2019.01.01
1    2017-08-13
2    2017/06/07
dtype: object

In [4]:
# 1) str 타입을 datetime 타입으로 변환 후 pandas 저장
# pd.to_datetime()
pd.Series(pd.to_datetime(str_date))

0   2019-01-01
1   2017-08-13
2   2017-06-07
dtype: datetime64[ns]

In [6]:
# 2) str 타입으로 저장 후 데이터 타입 변경
# sr.astype('데이터타입')
pd.Series(str_date).astype('datetime64')

0   2019-01-01
1   2017-08-13
2   2017-06-07
dtype: datetime64[ns]

In [7]:
# 날짜 데이터2 : timestamp 타입
# 1234000, 1230405, 12350600
# timestamp : 기준시각(UTC 1970.1.1 00:00:00)을 기준으로 몇 초 경과했는지의 기간
stamp_date = [1234000, 1234101, 1234202, 1234444, 1234900]

In [8]:
# 숫자 타입으로 저장
pd.Series(stamp_date)

0    1234000
1    1234101
2    1234202
3    1234444
4    1234900
dtype: int64

In [9]:
# datetime 타입으로 변환 후 저장
# timestamp & pd.to_datetime() 기본 단위 : ns(nano seconds)
# pd.to_datetime 파라미터
# unit : ns(default), D(days), s(seconds), ms(milli seconds) ...
pd.Series(pd.to_datetime(stamp_date))

0   1970-01-01 00:00:00.001234000
1   1970-01-01 00:00:00.001234101
2   1970-01-01 00:00:00.001234202
3   1970-01-01 00:00:00.001234444
4   1970-01-01 00:00:00.001234900
dtype: datetime64[ns]

In [10]:
# unit = s
pd.Series(pd.to_datetime(stamp_date, unit='s'))

0   1970-01-15 06:46:40
1   1970-01-15 06:48:21
2   1970-01-15 06:50:02
3   1970-01-15 06:54:04
4   1970-01-15 07:01:40
dtype: datetime64[ns]

In [12]:
# unit = D
pd.Series(pd.to_datetime([100,200,300,400], unit='D'))

0   1970-04-11
1   1970-07-20
2   1970-10-28
3   1971-02-05
dtype: datetime64[ns]

In [13]:
# unit = ms
pd.Series(pd.to_datetime(stamp_date, unit='ms'))

0   1970-01-01 00:20:34.000
1   1970-01-01 00:20:34.101
2   1970-01-01 00:20:34.202
3   1970-01-01 00:20:34.444
4   1970-01-01 00:20:34.900
dtype: datetime64[ns]

#### 2. 라벨 형식 통일
- 데이터 인코딩 작업에 포함

In [ ]:
# map() / apply()
# dict => dict(), zip(), range(), enumerate()
# def
# lambda

In [14]:
# gender 컬럼
# 0001012
# 0: F, 1 :M, 2:N
df = pd.DataFrame({'gender':[0,0,0,1,0,1,2]})
df

gender
0       0
1       0
2       0
3       1
4       0
5       1
6       2

In [16]:
dict(zip(range(3), ['F','M','N']))

{0: 'F', 1: 'M', 2: 'N'}

In [25]:
tmp = {}
# enumerate()는 range() 함수를 자동실행해서 숫자를 생성해준다.
for k,v in enumerate(['F','M','N']):
    tmp[k] = v

In [26]:
tmp

{0: 'F', 1: 'M', 2: 'N'}

In [27]:
df['gender'].map(tmp)

0    F
1    F
2    F
3    M
4    F
5    M
6    N
Name: gender, dtype: object

In [31]:
# replace() 
df['gender'] = df['gender'].replace(0,'F')
df['gender'] = df['gender'].replace(1,'M')
df['gender'] = df['gender'].replace(2,'N')

In [32]:
df['gender']

0    F
1    F
2    F
3    M
4    F
5    M
6    N
Name: gender, dtype: object

#### 3. 문자 형식(대소문자, 기호 등) 통일

In [33]:
# 샘플 데이터프레임 생성
# 컬럼 : Name, Age
# Jane, Jessie Alex
# 18,19,20
df1 = pd.DataFrame({'Name':['Jane', 'Jessie', 'Alex'],
                    'Age':[18,19,20]})
df1

Name  Age
0    Jane   18
1  Jessie   19
2    Alex   20

In [ ]:
# for문
# 새로운 리스트에 새로운 컬럼 저장한 후 df.columns = 새로운 리스트
# df.rename({old:new}, axis=1, inplace=True)

In [41]:
# 컬럼명을 모두 소문자로 한번에 변경
# str 타입인 컬럼에 대해 str 메서드를 적용하는 방법
df1.columns = df1.columns.str.lower()

In [42]:
df1

name  age
0    Jane   18
1  Jessie   19
2    Alex   20

In [52]:
# 텍스트 데이터를 가지고 있는 컬럼에 대해서 값을 모두 소문자로 통일
df1.dtypes

name    object
age      int64
100      int64
dtype: object

In [53]:
df1['name'].dtypes

dtype('O')

In [56]:
for col in df1.columns:
    if df1[col].dtypes == 'O':
        df1[col] = df1[col].apply(lambda x: x.lower())    

In [57]:
df1

name  age  100
0    jane   18   10
1  jessie   19   20
2    alex   20   30

In [ ]:
# 컬럼명이 텍스트인 케이스만 처리
# 컬럼명이 숫자인 컬럼 추가
df1[100] = [10,20,30]

In [76]:
# df 컬럼 원복
df1.columns = ['NAME', 'AGE', 100]

In [77]:
df1

NAME  AGE  100
0    jane   18   10
1  jessie   19   20
2    alex   20   30

In [78]:
# 값 자체를 확인
tmp = []
for col in df1.columns:
    if col != 100:
#       리스트로 전체 컬럼을 전달하지 않고 일부 컬럼만 수정
#       df1.rename({col:col.lower}, axis=1, inplace=True)  
        tmp.append(col.lower())
    
tmp.append(100)

In [79]:
df1.columns = tmp

In [80]:
df1

name  age  100
0    jane   18   10
1  jessie   19   20
2    alex   20   30

#### 데이터 값에 대한 처리
- 결측값
- 이상치
- 단순 중복 데이터
- 동일한 의미, 다른 명칭의 중복 데이터
- 중복속성(다중공선성)
- 불규칙한 데이터 수집(간격, 단위)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터 적재
sample = pd.read_csv('csv_exam_nan.csv')
sample

math  english  science
0  70.0      NaN      NaN
1  75.0     65.0     80.0
2   NaN      NaN      NaN
3  56.0     89.0      NaN
4  89.0     95.0     83.0
5  90.0    100.0     89.0

#### 결측치 처리 - 삭제
- 결측치가 하나라도 있는 레코드 삭제 
- 모든 값이 결측인 레코드 삭제 
- 결측치가 하나라도 있는 데이터만 선택

In [82]:
# 결측치가 하나라도 있는 레코드 삭제
# df.dropna(how='any'(기본동작), inplace=True)
sample.dropna()

math  english  science
1  75.0     65.0     80.0
4  89.0     95.0     83.0
5  90.0    100.0     89.0

In [83]:
sample

math  english  science
0  70.0      NaN      NaN
1  75.0     65.0     80.0
2   NaN      NaN      NaN
3  56.0     89.0      NaN
4  89.0     95.0     83.0
5  90.0    100.0     89.0

In [84]:
# 모든 값이 결측인 레코드 삭제
sample.dropna(how='all')

math  english  science
0  70.0      NaN      NaN
1  75.0     65.0     80.0
3  56.0     89.0      NaN
4  89.0     95.0     83.0
5  90.0    100.0     89.0

In [90]:
# 결측치가 하나라도 있는 데이터만 선택
sample[sample.isnull().any(axis=1)]

math  english  science
0  70.0      NaN      NaN
2   NaN      NaN      NaN
3  56.0     89.0      NaN

#### 결측치 처리 - 대체값
- 연속형 : 임의값(0), mean, median, 예측값, 도메인지식 활용
- 명목형 : mode(최빈값), 예측값, 도메인지식 활용

In [92]:
# 연속형 - 임의값 대체
# df.fillna(k)
sample.isnull().sum()

math       1
english    2
science    3
dtype: int64

In [94]:
sample.fillna(0)

math  english  science
0  70.0      0.0      0.0
1  75.0     65.0     80.0
2   0.0      0.0      0.0
3  56.0     89.0      0.0
4  89.0     95.0     83.0
5  90.0    100.0     89.0

In [93]:
sample.fillna(0).isnull().sum()

math       0
english    0
science    0
dtype: int64

In [95]:
sample

math  english  science
0  70.0      NaN      NaN
1  75.0     65.0     80.0
2   NaN      NaN      NaN
3  56.0     89.0      NaN
4  89.0     95.0     83.0
5  90.0    100.0     89.0

In [102]:
# mean - 1) 전체 데이터의 평균값
sample.mean()

math       76.00
english    87.25
science    84.00
dtype: float64

In [98]:
# np 타입 연산은 하나라도 NaN 값이 있으면 결과는 NaN
sample.values.sum()

nan

In [106]:
total_avg = sample.fillna(0).values.mean()

In [108]:
sample.fillna(total_avg)

math  english  science
0  70.0     54.5     54.5
1  75.0     65.0     80.0
2  54.5     54.5     54.5
3  56.0     89.0     54.5
4  89.0     95.0     83.0
5  90.0    100.0     89.0

In [111]:
# mean - 2) 결측이 있는 속성의 평균값
# 1. 속성별로 평균 => df 컬럼별 평균 => pandas 연산은 NaN 제외하고 연산
# 2. 속성별로 fillna(1번값)
m_avg = sample.mean()[0]
e_avg = sample.mean()[1]
s_avg = sample.mean()[2]

In [116]:
sample['math'].fillna(m_avg, inplace=True)
sample['science'].fillna(s_avg, inplace=True)
sample['english'].fillna(e_avg, inplace=True)

In [117]:
sample.isnull().sum()

math       0
english    0
science    0
dtype: int64

In [3]:
sample.head()

math  english  science
0  70.0      NaN      NaN
1  75.0     65.0     80.0
2   NaN      NaN      NaN
3  56.0     89.0      NaN
4  89.0     95.0     83.0

In [5]:
sample.isnull().sum()

math       1
english    2
science    3
dtype: int64

In [6]:
sample.shape

(6, 3)

In [ ]:
# median - 

In [15]:
# median 
# 전체 데이터를 크기 순으로 나열했을 때 중간위치
# total_avg : 54.5
# total_medi : 86
x = pd.Series(sample.values.reshape(18)).median()

In [16]:
# 찾은 중위값으로 df의 결측치 대체
sample.fillna(x)

math  english  science
0  70.0     86.0     86.0
1  75.0     65.0     80.0
2  86.0     86.0     86.0
3  56.0     89.0     86.0
4  89.0     95.0     83.0
5  90.0    100.0     89.0

In [19]:
# 속성별 중위값 찾기
# df.median() : 컬럼별 값의 중위값 반환
m = sample.median()[0]
e = sample.median()[1]
s = sample.median()[2]

In [20]:
m,e,s

(75.0, 92.0, 83.0)

In [23]:
# df[컬럼].fillna() : 특정 컬럼에만 특정 값으로 결측치 대체
sample['math'].fillna(m)

0    70.0
1    75.0
2    75.0
3    56.0
4    89.0
5    90.0
Name: math, dtype: float64

In [ ]:
# mode - 최빈값(가장 많이 나온 값)
# 범주형 변수에서 존재하는 결측치 대체 값으로 사용
# 연속형에서는 사용하지 않음
# 1. describe()
# 2. value_counts()
# 3. collections 라이브러리의 Counter 클래스
# 4. mode()

In [25]:
sample2 = pd.DataFrame({'label' : ['A','A','B','C','C','C','D','B']})
sample2.shape

(8, 1)

In [29]:
# describe()에서 최빈값 찾기
sample2.describe().loc['top'][0]

'C'

In [36]:
# sr.value_counts()
# 최빈값이 가장 위에 정렬되서 반환
sample2['label'].value_counts().index[0]

'C'

In [37]:
from collections import Counter

In [ ]:
# 1. 라이브러리/클래스를 불러오기
# 2. 사용하려는 클래스 객체 생성
# 3. 객체의 메서드를 사용

In [38]:
colors = ['red','red', 'blue','blue', 'white','white','white']

In [39]:
counter = Counter(colors)

In [40]:
counter

Counter({'red': 2, 'blue': 2, 'white': 3})

In [45]:
# 범주형 변수와 빈도 값을 많이 나온 순서대로 정렬하여 반환
# dict.items() 형식과 유사하게 반환
counter.most_common()[0][0]

'white'

In [ ]:
# 최빈값을 반환하는 사용자 정의함수 1
# 인자값 : 리스트
# 반환값 : 최빈값(범주값)

In [46]:
# 정의문
def mode_finder(x):
    counter = Counter(x)
    mode = counter.most_common()[0][0]
    return mode

In [47]:
# 실행문
# 반환값 : c
mode_finder(['a','b','c','c','d'])

'c'

In [48]:
# 문제점
# 동일한 빈도를 가진 최빈값이 있을 경우에 정확한 결과가 아님
# 수정사항) 동일 최고 빈도가 있을 경우에는 모든 최빈값을 반환
mode_finder(['a','b','c','c','b'])

'b'

In [53]:
# 동일 최빈값이 2개 이상일 경우
# 1. 최빈값 : 범주, 빈도
# 2. 최빈값의 빈도와 동일한 빈도가 있는지 확인
# 3. 있으면 해당 범주를 함께 반환
def mode_finder2(x):
    counter = Counter(x)
    result = counter.most_common()  # [(cat1, cnt1), (cat2, cnt2)]
    mode_value = result[0][1]
    modes = [mode_value]
    
    for i in result:
        if i[1] == mode_value:
            modes.append(i[0])
            
    return modes

In [54]:
mode_finder2(['a','a','b','b','c','c'])

[2, 'a', 'b', 'c']

In [57]:
# 데이터프레임에 적용
Counter(sample2['label']).most_common()

[('C', 3), ('A', 2), ('B', 2), ('D', 1)]

### 데이터 단위 통일

#### 표준화(Standardization)
- 평균을 기준으로 얼마나 떨어져 있는지를 파악
- sklearn에서 제공하는 전처리 모듈/클래스
    - preprocessing 모듈
        - scaler() : 전체 자료의 분포를 평균 0, 표준편차 1이 되도록 스케일링
        - minmax_scale() : 최대/최소값이 각각 1, 0이 되도록 스케일링
        - StandardScaler() : scaler() 함수와 동일한 동작
            
<img src='img/stand.png' width='600' height='400' align='left'>

- 표준화 : (요소값(하나의 데이터) - 평균) / 표준편차
- 삼성전자 vs 작은회사 주식 시세
- 몸무게 vs 키
    - 표준화 결과 : 몸무게 음수, 키 양수
    - 해석 : 몸무게는 평균 이하, 키는 평균 이상(=>마른몸)

In [58]:
# 전처리 기능을 제공하는 scikitlearn 라이브러리 및 모듈 가져오기
from sklearn.preprocessing import scale, minmax_scale

In [59]:
# -3 이상 5 이하의 정수를 값으로 가지는 9행 1열 배열 생성
x = (np.arange(9) - 3).reshape(-1,1)

In [61]:
x.shape

(9, 1)

In [ ]:
# 데이터프레임 생성
# 3개 컬럼 : x, scale-x, minmax-x

In [62]:
scale(x)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


array([[-1.54919334],
       [-1.161895  ],
       [-0.77459667],
       [-0.38729833],
       [ 0.        ],
       [ 0.38729833],
       [ 0.77459667],
       [ 1.161895  ],
       [ 1.54919334]])

In [63]:
df = pd.DataFrame(np.hstack([x, scale(x), minmax_scale(x)]),
                 columns=['x', 'scale(x)', 'minmax_scale(x)'])

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64.
  warnings.warn(msg, DataConversionWarning)


In [64]:
df

x  scale(x)  minmax_scale(x)
0 -3.0 -1.549193            0.000
1 -2.0 -1.161895            0.125
2 -1.0 -0.774597            0.250
3  0.0 -0.387298            0.375
4  1.0  0.000000            0.500
5  2.0  0.387298            0.625
6  3.0  0.774597            0.750
7  4.0  1.161895            0.875
8  5.0  1.549193            1.000

In [71]:
# 전체 데이터에 대해 컬럼별 평균, 표준편차 비교
# df['x'].mean()
np.mean(df['x'])
# df['x'].std()   # 2.7386127875258306
np.std(df['x'])  # 2.581988897471611

2.581988897471611

In [73]:
print('original : ',  np.mean(df['x']), np.std(df['x']))
print('scale(x) : ',  np.mean(df['scale(x)']), np.std(df['scale(x)']))
print('minmax_scale(x) : ',  np.mean(df['minmax_scale(x)']),
      np.std(df['minmax_scale(x)']))

original :  1.0 2.581988897471611
scale(x) :  0.0 1.0
minmax_scale(x) :  0.5 0.3227486121839514


In [74]:
# StandardScaler 클래스 가져오기
# 1. 클래스 객체 생성
# 2. 객체의 fit() 메서드로 표준화 변환 계수 추정
# 3. fit()을 실행한 객체의 transform() 메서드로 표준화 결과 반환
# 2~3번을 한 번에 실행 : fit_transform()
from sklearn.preprocessing import StandardScaler

In [75]:
scaler = StandardScaler()

In [83]:
df['x'].values.reshape(-1,1)

(9,)

In [85]:
x

array([[-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5]])

In [84]:
scaler.fit(df['x'].values.reshape(-1,1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [88]:
scaled_x = scaler.transform(df['x'].values.reshape(-1,1))

In [89]:
tmp = pd.DataFrame(scaled_x)
tmp.head()

0
0 -1.549193
1 -1.161895
2 -0.774597
3 -0.387298
4  0.000000

In [90]:
np.std(tmp[0])

1.0

In [91]:
np.mean(tmp[0])

0.0

### 정규화(Normalizaion)

- 정규화는 서로 다른 단위의 다차원 독립 변수에 대해 각 변수들의 상대적 크기 비교
- 정규화 결과값은 0 ~ 1 사이의 값을 가짐
- 단위가 서로 다른 경우
- 0이 아주 많은 경우
- sklearn 라이브러리에서 제공하는 클래스
    - normalize()
    
<img src='img/normal.png' width='600' height='400' align='left'>

- 정규화 : (요소값 - 최소값) / (최대값 - 최소값)
- 전체 구간을 0 ~ 100으로 설정해서 데이터에 상대적 크기/위치를 관찰

In [92]:
from sklearn.preprocessing import normalize

In [96]:
# 구조 : 5행 2열 2d array
# 첫번째 열 : -20 ~ -16 까지의 정수
# 두번째 열 : -2 ~ +2까지의 정수
x = np.vstack([(np.arange(5) - 20),(np.arange(5) - 2)]).T

In [97]:
# 표준화(스케일링) 적용
y1 = scale(x)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [101]:
y1

array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

In [99]:
# 정규화 적용
y2 = normalize(x)

In [102]:
y2

array([[-0.99503719, -0.09950372],
       [-0.99861783, -0.05255883],
       [-1.        ,  0.        ],
       [-0.99827437,  0.05872202],
       [-0.99227788,  0.12403473]])

In [ ]:
# 정규화 여부 확인
# np.linalg.norm(data, axis=1)
# 결과값 : 값의 단위

In [106]:
# 정규화
# print(y2)
print(np.linalg.norm(y2, axis=1))

[1. 1. 1. 1. 1.]


In [105]:
# 표준화
print(np.linalg.norm(y1, axis=1))

[2. 1. 0. 1. 2.]
