In [1]:
# 라이브러리 맟 사용자 정의함수 불러오기
import numpy as np

## 산술연산

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) : dot()

In [3]:
# 아이템 : 1 이상 10 미만의 1씩 증가하는 숫자
# 구조 : 3x3
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# 아이템 : 1
# 구조 : 3x3
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# 아이템 :  10이상 22미만의 1씩 증가하는 숫자
# 구조 : 3x4
c = np.arange(10, 22).reshape(3,4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 더하기

- 배열 + 배열
- np.add(arr1, arr2)

In [9]:
# 산술 연산자
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a+b

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [11]:
# np 함수
np.add(a,b)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [12]:
# 구조가 다른 배열간의 산술연산(+)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [13]:
np.add(a,c)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### 빼기

- 배열 - 배열
- np.subtract(arr1, arr2)

In [15]:
# 산술연산자
a - b
b - a

array([[ 0., -1., -2.],
       [-3., -4., -5.],
       [-6., -7., -8.]])

In [17]:
# np 함수
np.subtract(a,b)
np.subtract(b,a)

array([[ 0., -1., -2.],
       [-3., -4., -5.],
       [-6., -7., -8.]])

### 나누기

- 배열 / 배열
- np.divide(arr1, arr2)

In [20]:
b2 = np.arange(3, 12).reshape(3,3)
b2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
# 산술연산자
a/b2

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ],
       [0.77777778, 0.8       , 0.81818182]])

In [22]:
b2/a

array([[3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333],
       [1.28571429, 1.25      , 1.22222222]])

In [24]:
#np 함수
np.divide(a,b2)
np.divide(b2,a)

array([[3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333],
       [1.28571429, 1.25      , 1.22222222]])

### 곱하기

- 배열 * 배열
- np.multiply(arr1, arr2)

In [25]:
# 산술연산자
a * b2

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [27]:
b2*a

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [30]:
# np 함수
np.multiply(a, b2)

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

### 내적(행렬곱)
- np.dot(a, b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [28]:
np.dot(a, b2)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

### 지수곱 표현

- 지수(exponent) : 부동 소수점으로 숫자를 표시할 때 거듭제곱을 사용하여 표현. <br>
(예) 2.14e+2 = 2.14 x 102 = 214 / 2.98e-8 = 2.98 x 10-8 = 0.0000000298
- np.exp(arr) : 밑(base)이 자연상수 e 인 지수함수로 변환(y = e**x)

In [31]:
# 지수함수
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### 제곱근

- np.sqrt(arr)

<img src='img/sqrt.gif' width='400' height='200' align='left'>

In [41]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [44]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

### Numpy 배열 연산

#### 2. 비교 연산

1) 요소
- 값에 대한 비교 : ==, !=
- 크기에 대한 비교 : >, <, >=, <=

2) 배열
- 두 배열 전체에 대한 비교 : np.array_equal(a, b)

In [45]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
# 두 배열의 요소에 대하여 값이 동일한지 비교
# 반환 : 원본 배열의 구조와 동일한 boolean indexing 값이 저장된 배열
a == b

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [52]:
# 두 배열의 요소에 대하여 값이 다른지 비교
a != b

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [53]:
# 두 배열의 요소에 대해 크기를 비교
a > b

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
# 두 배열 전체에 대한 비교 : 두 배열이 완벽하게(요소 전체) 똑같은 배열인지 확인
# 반환값 : 하나의 T/F
np.array_equal(a, b)

False

In [57]:
b2 = b.copy()

In [58]:
np.array_equal(b, b2)

True

### Numpy 배열 연산

3. 집계 함수

    - Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
    - 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
    - axis
        - axis = None <br>
        전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 함수로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median()
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef()
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique()

In [59]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
sum(list(np.ravel(a)))

45

In [61]:
# 합계 - 배열 요소의 전체 합계
# 1) 배열 타입의 메서드 : arr.sum()
# 2) numpy 함수 : np.sum(arr)
a.sum()

45

In [62]:
np.sum(a)

45

In [66]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
# 합계 - 행 기준(axis=1)
# 결과값 : [첫번째행 총합, 두번째행총합...]
a.sum(axis=1)
np.sum(a, axis=1)

array([ 6, 15, 24])

In [69]:
# 합계 - 열 기준(axis=0)
# 결과값 : [첫번째열합, 두번째열합...]
a.sum(axis=0)
np.sum(a, axis=0)

array([12, 15, 18])

In [70]:
# 최소값 - 전체 기준
# 1) 배열 타입의 메서드 : arr.min()
# 2) numpy 함수 : np.min(arr)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
a.min()
np.min(a)

1

In [73]:
# (참고) 리스트 요소 중에 최소 값 찾기
x = [1,2,3,4]
min(x)

1

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
# 최소값 - 행 기준(axis = 1)
# 결과값 : [첫번째행최소값,두번째행최소값....]
a.min(axis=1)

array([1, 4, 7])

In [78]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
# 최소값 - 열 기준(axis = 0)
# 결과값 : [첫번쨰열최소, 두번쨰열최소, 세번째열최소]
a.min(axis=0)

array([1, 2, 3])

In [79]:
# 최대값 - 전체 기준
# 1) 배열 타입의 메서드 : arr.max()
# 2) numpy 함수 : np.max(arr)
a.max()

9

In [81]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
# 최대값 - 행 기준(axis=1)
a.max(axis=1)

array([3, 6, 9])

In [83]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
# 최대값 - 열 기준(axis=0)
a.max(axis=0)

array([7, 8, 9])

In [85]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
# 누적합계 - 전체 기준
# 1) 배열 타입의 메서드 : a.cumsum()
# 2) numpy 함수 : np.cumsum(a)
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [87]:
# 누적합계 - 행 기준
# 결과값 : 
a.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [88]:
# 누적합계 - 열 기준
# 결과값 : 
a.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [97]:
a[2][2] = 90
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [98]:
# 평균 - 전체 기준
# 1) 배열 타입의 메서드 : a.mean()
# 2) numpy 함수 : np.mean(a)
a.mean()

14.0

In [91]:
# 평균 - 행 기준
a.mean(axis=1)

array([2., 5., 8.])

In [92]:
# 평균 - 열 기준
a.mean(axis=0)

array([4., 5., 6.])

In [99]:
# 중앙값 - 전체 기준
# numpy 함수: np.median(a)
np.median(a)

5.0

In [100]:
# 중앙값 - 행 기준
np.median(a, axis=1)

array([2., 5., 8.])

In [102]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [101]:
# 중앙값 - 열 기준
np.median(a, axis=0)

array([4., 5., 6.])

In [103]:
# 상관계수 : 두 데이터 간의 상관관계의 방향과 강한 정도(-1<=corr<=1)
# numpy 함수 : np.corrcoef(arr1, arr2)
x = np.array([1,2,3,4,5])
y = -x.copy()
# y = np.array([-1,-2,-3,-4,-5])

In [105]:
y

array([-1, -2, -3, -4, -5])

In [108]:
# 자기자신과의 상관관계 
# 결과 : 대칭형 매트릭스
# 상위삼각형 또는 하위삼각형 둘 중 하나만 해석하면 된다.
# 가운데 대각선은 자기자신과의 상관관계이므로 항상 1
np.corrcoef(x, x)

array([[1., 1.],
       [1., 1.]])

In [111]:
y = np.array([7.3, 8.2, 10, 13.1, 15.5])

In [112]:
# 서로 다른 배열 2개를 이용한 상관계수 matrix
np.corrcoef(x, y)

array([[1.        , 0.98220321],
       [0.98220321, 1.        ]])

In [110]:
# 3개 이상의 배열에 대한 상관계수 : 구할 수 없다.
np.corrcoef(x, y, -y)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### (참고) 데이터가 퍼져있는 정도를 나타내는 개념

1. 표준편차(std/sd) : 단위에 대한 보정이 들어가 있지 않아서 상대적인 비교가 어려움
2. 변동계수(cv) : 편차/평균
    - 두 개 이상의 변수(서로 다른 단위를 사용하는 경우)에 대해 데이터가 퍼져있는 정도를 파악하는 경우

In [114]:
# 표준편차 - 전체 기준
# 1) 배열 타입의 메서드 : arr.std()
# 2) numpy 함수 : np.std(arr)
a.std()

26.956755492207638

In [115]:
# 표준편차 - 행 기준
a.std(axis=1)

array([ 0.81649658,  0.81649658, 38.89301565])

In [116]:
# 표준편차 - 열 기준
a.std(axis=0)

array([ 2.44948974,  2.44948974, 40.32369031])

In [119]:
a[0] = 1

In [121]:
# 고유값 - 전체 값에 적용
# numpy 함수 : np.unique(a)
np.unique(a)

array([ 1,  4,  5,  6,  7,  8, 90])

In [127]:
a1 = np.random.randint(0,4,(3,3))
a1

array([[0, 2, 0],
       [2, 3, 3],
       [3, 1, 1]])

In [137]:
# 동일한 행 추가
temp = np.array([3,1,1]).reshape(1,3)
a1 = np.append(a1, temp, axis=0)

In [138]:
a1

array([[0, 2, 0],
       [2, 3, 3],
       [3, 1, 1],
       [3, 1, 1]])

In [141]:
np.unique(a1)

array([0, 1, 2, 3])

In [139]:
# 고유값 - 열 기준
# 결과값 : 열 요소의 고유한 조합 반환
np.unique(a1, axis=1)

array([[0, 0, 2],
       [2, 3, 3],
       [3, 1, 1],
       [3, 1, 1]])

In [140]:
# 고유값 - 행 기준
# 결과값 : 행 요소의 고유값 X 행 요소의 고유한 조합 반환
np.unique(a1, axis=0)

array([[0, 2, 0],
       [2, 3, 3],
       [3, 1, 1]])

#### 브로드캐스팅(BroadCasting)

- 서로 다른 구조(shape)를 가진 배열에 대해 연산을 수행할 때 구조를 맞추는 과정
- 배열과 스칼라값 간의 연산
- 배열과 배열 간의 연산
- 브로드캐스팅 규칙 : 축의 길이가 일치하거나 둘 중 하나의 길이가 1인 두 배열에 대해 호환성을 가짐
<img src='img/broadcast.png' width='600' height='400' align='left'>

In [143]:
# (연결개념) 구조가 동일한 배열에 대한 연산 
a

array([[ 1,  1,  1],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [144]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 1. 배열과 값(single value, scala)

- 스칼라 값을 배열의 구조와 동일한 배열로 변형하여 연산 수행

In [145]:
# 구조가 다른 배열 간의 연산
# a 배열의 모든 요소에 10을 더하기
a + 10

array([[ 11,  11,  11],
       [ 14,  15,  16],
       [ 17,  18, 100]])

In [146]:
# 브로드캐스팅 과정
# 1. 스칼라값이 배열로 변형
scalar_arr = np.full_like(a, 10)
scalar_arr

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [148]:
a + 10

array([[ 11,  11,  11],
       [ 14,  15,  16],
       [ 17,  18, 100]])

In [147]:
# 배열 + 스칼라 변형 배열
a + scalar_arr

array([[ 11,  11,  11],
       [ 14,  15,  16],
       [ 17,  18, 100]])

#### 2. 서로 다른 구조의 배열

- 행, 열의 최대 길이를 기준으로 구조를 생성한 배열로 변형하여 연산 수행
- 확장된 행, 열에 대해서 기존 배열과 동일한 데이터로 구성

In [150]:
# 1행 4열의 구조에서 1,2,3,4 를 값으로 가지는 배열 x 생성
# 4행 1열의 구조에서 1,2,3,4 를 값으로 가지는 배열 y 생성
x = np.array([1,2,3,4]).reshape(1,4)
y = x.reshape(4,1).copy()
# y = np.array([1,2,3,4]).reshape(4,1)

In [151]:
x

array([[1, 2, 3, 4]])

In [152]:
y

array([[1],
       [2],
       [3],
       [4]])

In [153]:
x+y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [155]:
# 브로드캐스팅 과정 : x
new_x = np.append(x, x, axis=0)

In [157]:
new_x = np.append(new_x, new_x, axis=0)

In [159]:
# 브로드캐스팅 과정 : y
new_y = np.append(y, y, axis=1)

In [161]:
new_y = np.append(new_y, new_y, axis=1)

In [162]:
# 1행 4열의 배열과 4행 1열의 배열의 브로드캐스팅 연산
new_x + new_y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [163]:
# 구조가 동일한 배열의 연산 결과와 동일
x+y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

### 벡터 연산

- 요소들에 대한 연산을 벡터 연산으로 처리하면 일반적인 for반복문으로  연산 작업을 처리하는 것 보다 월등히 뛰어난 처리 속도로 효율적인 작업 가능

In [164]:
# 0부터 시작하여 1000,000개의 요소를 가진 배열 생성
x = np.arange(1000000)
len(x)

1000000

In [166]:
%%time
# 셀의 동작 시간을 알려주는 iPython 명령어, 셀의 가장 위에 위치(주석도 있으면 안됨)
# 1s = 1000ms(밀리세컨즈) = 1,000,000µs/ns(마이크로세컨즈/나노초)
# 반복문을 통한 합계
# 290
result = 0
for i in x:
    result += i
    
result

Wall time: 138 ms


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in long_scalars
  """


In [172]:
%%time
# 벡터 연산을 통한 합계 연산
#  3.99 ms

np.sum(x)

Wall time: 0 ns


1783293664

In [170]:
%%time
# 파이썬 내장함수와 넘파이 배열 타입을 통한 합계 연산
# 140
sum(x)

Wall time: 67.8 ms


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in long_scalars
  


1783293664

In [171]:
%%time
# 파이썬 내장함수와 파이썬 리스트 타입을 통한 합계 연산
# 184
sum(list(x))

Wall time: 80.8 ms


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in long_scalars
  


1783293664

## 연습문제

1. 0 이상 5미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 배열 생성
2. 1번 배열의 모든 요소에 대해 동일하게 10씩 더하기

In [176]:
a = np.arange(0,5).reshape(1,5)

In [177]:
a

array([[0, 1, 2, 3, 4]])

In [178]:
a  + 10

array([[10, 11, 12, 13, 14]])

3. 자유 범위에서 1씩 증가하는 숫자를 데이터로 가지고 4행 3열의 구조를 가진 배열 생성
4. 배열의 각 로우(행)에 로우별(행별) 평균을 빼기 => 행별 요소값의 편차를 계산할 수 있음

In [179]:
# 데이터 생성
x = np.arange(5, 17).reshape(4,3)

In [180]:
x

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [184]:
# 행별 평균 구하기
row_mean = x.mean(axis=1)

In [185]:
# 행 마다 행별 평균 빼기
x - row_mean

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [186]:
row_mean2 = row_mean.reshape(4,1)

In [187]:
row_mean2

array([[ 6.],
       [ 9.],
       [12.],
       [15.]])

In [188]:
x - row_mean2

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])