In [96]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    shape : {}  
    dimension : {}  
    data :\n {}
    '''.format(nparr.shape, nparr.ndim,nparr))

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
    
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [ ]:
# 1차원 배열 생성
# 아이템 : 0,1,2,3,4
x = np.arange(0,5)
np_print(x)

In [ ]:
# 아이템 순서를 뒤집어서 나열
x[::-1]

In [ ]:
# arr.sort() : 원본 객체에 저장됨을 주의
x[::-1].sort()

In [ ]:
x[::-1]

In [ ]:
x

In [ ]:
# 다시 오름차순 정렬
x1 = np.sort(x)
np_print(x1)

In [ ]:
x

In [2]:
# 아이템 : 0 이상 10 미만의 범위에서 5개의 무작위 정수값
# 구조 : 1d => 5개 (5,)
a = np.random.randint(0, 10, 5)
np_print(a)


    shape : (5,)  
    dimension : 1  
    data :
 [4 0 4 7 9]
    


In [ ]:
# 오름차순 정렬
np.sort(a)

In [ ]:
# 내림차순 정렬
a.sort()  # 3,7,7,8,8
a

In [ ]:
a[::-1]

In [3]:
# 오름차순된 정렬 순서
np.sort(a)

array([0, 4, 4, 7, 9])

In [4]:
a

array([4, 0, 4, 7, 9])

In [5]:
np.argsort(a)

array([1, 0, 2, 3, 4], dtype=int64)

In [7]:
# 아이템 : 0 이상 1미만의 범위에서 무작위 실수값을 가지는 3x3
# np.random.random
a = np.random.random((3,3))
b = np.random.random((3,3))
np_print(a)
np_print(b)


    shape : (3, 3)  
    dimension : 2  
    data :
 [[0.37713917 0.99051673 0.05452122]
 [0.09365204 0.124047   0.03723359]
 [0.6588668  0.03284879 0.93530558]]
    

    shape : (3, 3)  
    dimension : 2  
    data :
 [[0.15377765 0.12758712 0.04829166]
 [0.34961602 0.43191087 0.18760475]
 [0.46152653 0.54275589 0.02970036]]
    


예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1 <br>
마지막 axis = 1 (행 기준 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [8]:
a

array([[0.37713917, 0.99051673, 0.05452122],
       [0.09365204, 0.124047  , 0.03723359],
       [0.6588668 , 0.03284879, 0.93530558]])

In [9]:
# 기본 방향 : 행 방향 정렬
np.sort(a)

array([[0.05452122, 0.37713917, 0.99051673],
       [0.03723359, 0.09365204, 0.124047  ],
       [0.03284879, 0.6588668 , 0.93530558]])

axis = 0 (열 기준 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>

In [10]:
a

array([[0.37713917, 0.99051673, 0.05452122],
       [0.09365204, 0.124047  , 0.03723359],
       [0.6588668 , 0.03284879, 0.93530558]])

In [11]:
# 열 기준 정렬
np.sort(a, axis=0)

array([[0.09365204, 0.03284879, 0.03723359],
       [0.37713917, 0.124047  , 0.05452122],
       [0.6588668 , 0.99051673, 0.93530558]])

In [12]:
# 내림차순 정렬
np.sort(a, axis=0)[::-1]

array([[0.6588668 , 0.99051673, 0.93530558],
       [0.37713917, 0.124047  , 0.05452122],
       [0.09365204, 0.03284879, 0.03723359]])

In [13]:
a

array([[0.37713917, 0.99051673, 0.05452122],
       [0.09365204, 0.124047  , 0.03723359],
       [0.6588668 , 0.03284879, 0.93530558]])

In [16]:
a[:, 0]

array([0.37713917, 0.09365204, 0.6588668 ])

In [17]:
# 첫번째 컬럼을 기준으로 내림차순 정렬1
a[a[:, 0].argsort()[::-1]]

array([[0.6588668 , 0.03284879, 0.93530558],
       [0.37713917, 0.99051673, 0.05452122],
       [0.09365204, 0.124047  , 0.03723359]])

In [20]:
-a[:, 0]

array([-0.37713917, -0.09365204, -0.6588668 ])

In [18]:
# 첫번째 컬럼을 기준으로 내림차순 정렬2
a[(-a[:, 0]).argsort()]

array([[0.6588668 , 0.03284879, 0.93530558],
       [0.37713917, 0.99051673, 0.05452122],
       [0.09365204, 0.124047  , 0.03723359]])

## 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱 : 하나의 요소에 대해 참조(접근/확인)
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [21]:
# 아이템 : 0부터 23까지 1씩 증가하는 값
# 구조 : 1차원
arr1 = np.arange(0, 24)
np_print(arr1)


    shape : (24,)  
    dimension : 1  
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [22]:
# 1차원 배열 인덱싱 : 1번 인덱스 요소
arr1[1]

1

In [23]:
# 1차원 배열 인덱싱 : 마지막 인덱스 요소
arr1[-1]

23

In [25]:
# 1차원 배열 인덱싱을 통한 값 수정 
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [27]:
len(arr1)

24

In [26]:
# 배열 arr1를 4 x 6 형태로 변환하여 2차원 배열 생성
# arr.reshape(row, col) 
arr1.size

24

In [29]:
arr2 = arr1.reshape(4,6)
np_print(arr2)


    shape : (4, 6)  
    dimension : 2  
    data :
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
    


In [33]:
# 2차원 배열 인덱싱 : 2d_array[행, (열)]
# 하나의 행에 접근 : 1행
# 반환값 : 1d array
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [34]:
# 하나의 열에 접근 : 모든 행에 대해 선택 한 후 열인덱스 지정
# 반환값 : 1d array
arr2[:, 0].shape

(4,)

In [36]:
# 하나의 값에 접근
# 3행 3열
arr2[2,2]

14

In [39]:
# 여러 개의 행에 접근
# 여러 개의 인덱스를 리스트로 묶어서 인덱싱
# 인덱스 : 1, 3 인 행에 접근
arr2[[1,3]]

array([[  6,   7,   8,   9,  10,  11],
       [ 18,  19,  20,  21,  22, 100]])

In [40]:
# 여러 개의 열에 접근
# 인덱스 : 0, 2번 열
arr2[:, [0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [ ]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열에 대해 모두 동일한 값으로 수정 : 단일 값
# 서로 다른 값으로 수정 : array, list => 참조한 배열 아이템 개수 = 전달하는 객체 아이템 개수

In [43]:
# 하나의 값으로 수정
arr2[0] = 9
arr2

array([[  9,   9,   9,   9,   9,   9],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22, 100]])

In [46]:
# 여러 개의 값으로 수정
arr2[0] = [0,1,2,9,9,9]

In [47]:
arr2

array([[  0,   1,   2,   9,   9,   9],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22, 100]])

In [48]:
# 3차원 배열 생성
# 아이템 : 0 이상 24미만의 정수
# 구조 : 2개층 4행 3열
arr3 = np.arange(0,24).reshape((2,4,3))
np_print(arr3)


    shape : (2, 4, 3)  
    dimension : 3  
    data :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
    


In [49]:
# 3차원 배열 인덱싱 : 3d_arry[층, 행, 열]
# 첫번째 층에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
# 첫번째 층, 2행에 접근
arr3[0,1]

array([3, 4, 5])

In [51]:
arr3[0][1]

array([3, 4, 5])

In [52]:
# 첫번째 층, 2행, 1열에 접근
arr3[0,1,0]

3

In [55]:
arr3[0][1][0]

3

In [57]:
# 3차원 배열 인덱싱을 통한 값 수정
# 동일한 값으로 수정 
arr3[0] = 1

In [58]:
arr3

array([[[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [60]:
# 하나의 층에 대해 서로 다른 값으로 수정 
# 리스트로 2d array : 다차원리스트 
arr3[0] = [[10, 1, 10],
           [1, 10, 1],
           [1, 10, 1],
           [1, 10, 1]]

In [61]:
arr3[0]

array([[10,  1, 10],
       [ 1, 10,  1],
       [ 1, 10,  1],
       [ 1, 10,  1]])

In [65]:
# 인덱스 배열을 전달하여 여러 개의 요소 참조
# (기존 인덱싱 방법) 
# arr3 1번째 층, 1번째행, 1번째 아이템(열)
# arr3 1번째 층, 2번째행, 2번째 아이템(열)
# arr3 1번째 층, 3번째행, 3번째 아이템(열)
arr3[0, 0, 0]   # 10
arr3[0, 1, 1]   # 10
arr3[0, 2, 2]   # 1

1

In [68]:
arr3

array([[[10,  1, 10],
        [ 1, 10,  1],
        [ 1, 10,  1],
        [ 1, 10,  1]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [72]:
# 여러 개의 인덱싱을 자료형으로 배열에 전달
# 3d_array[[층1, 행1, 열1], [층2, 행2, 열2], [층3, 행3, 열3]]
# 3d_array[[층], [행], [열]]
arr3[0,[[0,1],[1,2]], [[0,1], [0,1]]]

array([[10, 10],
       [ 1, 10]])

In [73]:
arr3[[0,0,0], [0,1,1], [0,2,2]]

array([10,  1,  1])

In [71]:
# 1번째 층에 0,1 행 두개
arr3[0, [[0,1],[1,2]]]

array([[[10,  1, 10],
        [ 1, 10,  1]],

       [[ 1, 10,  1],
        [ 1, 10,  1]]])

### 2. 슬라이싱 : 여러 개의 요소에 대해 참조
- axis 별로 범위 지정
    - from_index : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [74]:
# 아이템 : 0부터 23까지 1씩 증가하는 정수
# 구조 : 1d
a = np.arange(0,24)
np_print(a)


    shape : (24,)  
    dimension : 1  
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [75]:
# 1차원 배열 슬라이싱 : 1번 인덱스 부터 4번 인덱스까지 접근
a[1:5]

array([1, 2, 3, 4])

In [76]:
# 간격 지정 : 기본값 = 1
# 1 ~ 4번 인덱스 & 간격 2
a[1:5:2]

array([1, 3])

In [78]:
# 2차원 배열로 변환
# 구조 : 6, 4
a2 = a.reshape(6,4)

In [79]:
np_print(a2)


    shape : (6, 4)  
    dimension : 2  
    data :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
    


In [80]:
# 2차원 배열 슬라이싱 : 1행(0)부터 4행(3)까지
# 2d_array[행:행:간격(, 열:열:간격)]
a2[:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
a2[:4:2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [83]:
# 행, 열에 대해 모두 부분적 슬라이싱
# 1행~4행 & 2열~4열
a2[:4, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [85]:
# 서로 다른 결과
# 행에 대해서 슬라이싱을 2번 한 결과
a2[:4][1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
# 2차원 배열 슬라이싱을 통한 값 수정
# 부분 배열 생성
# 1행~4행 & 2열~4열
sample = a2[:4, 1:]

In [90]:
# 2~3 & 0~1
sample[2:, :2] = 333

In [91]:
# 배열 결과 확인
sample

array([[  1,   2,   3],
       [  5,   6,   7],
       [333, 333,  11],
       [333, 333,  15]])

In [92]:
# 원본 배열 확인
a2

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8, 333, 333,  11],
       [ 12, 333, 333,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [95]:
# 2차원 배열 슬라이싱 :연속되지 않은 범위의 열에 대한 인덱싱
# step1. 전체 행에 접근
# stpe2. 멀티 인덱싱
arr2[:, [1, -1]]

array([[  1,   9],
       [  7,  11],
       [ 13,  17],
       [ 19, 100]])

### 연습문제

아래 정보는 학생들의 학번, 영어 성적, 국어 성적, 수학 성적 정보 입니다. <br>
해당 정보를 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 국어 성적, 네번째 행에 수학 성적을 저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열(column)을 정렬하세요.

<img src='img/sort_q1.png' align='left' width=300>

In [122]:
data = [[1,2,3,4],
        [70,97,45,56],
        [87,84,33,67],
        [46,80,75,78]
        ]
arr = np.array(data)

np_print(arr)


    shape : (4, 4)  
    dimension : 2  
    data :
 [[ 1  2  3  4]
 [70 97 45 56]
 [87 84 33 67]
 [46 80 75 78]]
    


In [ ]:
# 열 위치 재배치
# 재배치 순서 = 영어 성적 순서(오름차순)

In [ ]:
# 인덱싱
# 개별 행에 접근 = 위치 바꾸기 = 모든 행이 동일한 위치
# 위치 바꾸기 => 멀티 인덱싱

In [103]:
arr[1]

array([70, 97, 45, 56])

In [110]:
# 2번 행을 오름차순 했을 때 순서를 1번 행에 적용
# 2번행을 오름차순한 정렬 순서 : np.argsort()
# 1번행에 적용
idx = np.argsort(arr[1])

In [109]:
# 멀티 인덱싱은 위치바꾸기로 적용할 수 있다.
arr[0][[2, 3, 0, 1]]

array([3, 4, 1, 2])

In [117]:
arr[0] = arr[0][idx]

In [118]:
arr[1] = arr[1][idx]

In [119]:
arr[2] = arr[2][idx]

In [120]:
arr[3] = arr[3][idx]

In [121]:
arr

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

In [134]:
# arr[arr[1].argsort()] = arr[[2, 3, 0, 1]] => 행 위치를 변경시키는 코드
arr[:][arr[1].argsort()]

array([[87, 84, 33, 67],
       [46, 80, 75, 78],
       [ 1,  2,  3,  4],
       [70, 97, 45, 56]])

In [126]:
# 열 위치만 변경시키는 코드
arr[:, arr[1].argsort()] 

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

### 조건 색인(Boolean Indexing)

- 배열의 요소에 대해 조건을 적용하여 True, False로 조건에 대한 결과 반환
- True에 해당하는 요소만 조회하여 조건을 만족하는 결과 반환

In [137]:
# 2차원 배열 
a2

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8, 333, 333,  11],
       [ 12, 333, 333,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [139]:
# 10 보다 큰 요소에 접근
# step1. 조건식을 연산자로 작성 -> 전체 배열에 적용
# 반환값 : T/F로 이루어진 전체 배열
a2 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [141]:
# step2. boolean indexing 결과를 전체 배열에 대해서 인덱싱처리
# 반환값 : 1d array => True인 결과만 추출됨
a2[a2 > 10]

array([333, 333,  11,  12, 333, 333,  15,  16,  17,  18,  19,  20,  21,
        22,  23])

In [142]:
# 개수
# len(), array.size
len(a2[a2 > 10])

15

In [143]:
a2[a2 > 10].size

15

In [147]:
(a2 > 10)

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [162]:
test = [[1,2,3], [1,1,1]]

In [167]:
sum(test)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [165]:
test2 = np.array(test)
test2

array([[1, 2, 3],
       [1, 1, 1]])

In [166]:
sum(test2)

array([2, 3, 4])

In [151]:
(a2 > 10)

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [160]:
sum((a2>10))

array([3, 4, 4, 4])

In [148]:
np.sum((a2 > 10))

15

In [145]:
# True : 1
(a2 > 10).sum()

15

In [168]:
a2

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8, 333, 333,  11],
       [ 12, 333, 333,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [171]:
# 짝수인 요소에 접근
a2[a2%2 == 0]

array([ 0,  2,  4,  6,  8, 12, 16, 18, 20, 22])

In [172]:
# 짝수인 요소의 개수 
# 조건문(조건식) 결과에 대한 개수 반환
(a2%2 == 0).sum()

10

In [173]:
# 조건색인 결과에 대한 개수 반환
a2[a2%2 == 0].size

10

In [174]:
# 짝수인 요소의 총합
a2[a2%2 == 0].sum()

108

In [175]:
np.sum(a2[a2%2 == 0])

108

### 배열 복사

- 인덱싱, 슬라이싱을 통해 반환된 배열은 원본 배열에 대해 독립적인 새로운 객체가 아닌 원본 배열과 종속적인 객체
- 원본과 독립적인 복사본인 배열을 생성 : arr.copy() / np.copy(arr)

In [176]:
# 파이썬 리스트 타입
a1 = [1,2,3]
a2 = [1,2,3]

In [177]:
# 서로 종속적인 객체
b = a1

In [178]:
b 

[1, 2, 3]

In [180]:
b[0] = 10
b

[10, 2, 3]

In [181]:
a1

[10, 2, 3]

In [182]:
# 서로 독립적인 객체
c = a2[:]

In [184]:
c[0] = 10

In [185]:
c

[10, 2, 3]

In [188]:
# Numpy 배열 타입
# 아이템 : 0부터 9까지의 범위에서 1씩 증가하는 값
# 구조 : 3x3
arr1 = np.arange(0,9).reshape(3,3)
np_print(arr1)


    shape : (3, 3)  
    dimension : 2  
    data :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
    


In [191]:
# 슬라이싱으로 배열 복사
arr2 = arr1[:, :]
np_print(arr2)


    shape : (3, 3)  
    dimension : 2  
    data :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
    


In [193]:
# 원본배열과의 관계 : 종속적인 관계의 객체 생성
# 1행 1열 값을 수정
arr2[0,0] = 100
arr2

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [194]:
arr1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [195]:
# 독립적인 복사본 배열 생성
# 배열 메서드 : 원본객체.copy()
# numpy 함수 : np.copy(원본객체)
arr3 = arr2.copy()
np_print(arr3)


    shape : (3, 3)  
    dimension : 2  
    data :
 [[100   1   2]
 [  3   4   5]
 [  6   7   8]]
    


In [197]:
# 원본배열과의 관계 : 독립적인 객체 생성
arr3[0,0] = 0
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [198]:
arr2

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])