In [ ]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    shape : {}  
    dimension : {}  
    data :\n {}
    '''.format(nparr.shape, nparr.ndim, nparr))

### 배열 변환

#### 1. 전치(Transpose) 
- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T : 행/열 인덱스가 바뀐 새로운 배열을 반환하며 원본은 변경되지 않음
    
<img src='img/transpose.png' width='200' height='200' align='left'>

In [ ]:
# 아이템 : 1 이상 13 미만의 정수값
# 구조 : 3x4
arr1 = np.arange(1,13).reshape(3,4)
np_print(arr1)

In [ ]:
arr1.reshape(4,3)

In [ ]:
# 전치행렬 생성
arr1.T

### 2. 배열 형태 변경
- arr.ravel(), np.ravel(arr)
    - 다차원 배열을 1차원 배열로 변환
    - np.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
    - arr.ravel() : 1차원으로 변환하는 배열의 요소가 변경되면 원본 배열에도 반영됨
- arr.reshape(new_shape), np.reshape(arr, new_shape)
    - 원본 배열 객체의 구조(shape)를 변경
    - 변경하려는 구조의 전체 요소 개수와 원본 배열의 전체 요소 개수가 동일해야 함
    - 변경하려는 구조의 튜플 중 하나의 원소는 -1로 대체할 수 있고 다른 하나의 원소를 기준으로 계산되어 사용됨
    - reshape() 메서드가 반환하는 배열의 요소가 변경되면 원본 배열에도 반영됨

In [ ]:
# 다차원 배열을 1차원 배열로 변환
# 메서드이지만 구조가 바뀌지 않음
# 1d = (12,)
arr2 = arr1.ravel()

In [ ]:
# 2d = (1,12)
arr1.reshape(1,12)

In [ ]:
# 변환 후 값 수정, 원본과 비교
arr2[0] = 100
arr2

In [ ]:
# ravel() 메서드의 반환 객체는 원본과 종속적인 객체
arr1

In [ ]:
# 원본배열을 2열을 기준으로 구조 변환
arr3 = arr2.reshape(-1, 2)

In [ ]:
# 변환 후 값 수정, 원본과 비교
# 1행 값을 모두 1로 수정
arr3[0] = 1
arr3

In [ ]:
arr2

#### 3. 요소 변경, 추가, 삭제

1) 요소 변경
- arr.resize((new_shape)), np.resize(arr, (new_shape))
    - 배열 메서드를 사용하면 원본 변경, np 함수를 사용하면 새로운 배열 반환
    - 배열의 구조(shape)를 변경하며 원본 배열의 요소 수와 동일하지 않아도 변경 가능
    - 변경되는 배열의 요소 수가 동일할 경우 : reshape() 메서드와 동일한 결과
    - 변경되는 배열의 요소 수가 더 많을 경우 
        - np.resize(arr, new_shape) : 원본을 변경하지 않고, 모자란 부분을 기존 배열 값에서 복사해서 추가
        - arr.resize(new_shape) : 원본을 변경하고, 모자란 부분을 0으로 채움
        - 공통적으로 new_shape은 튜플로 추가
    - 변경되는 배열의 요소 수가 더 작을 경우 : 마지막 남은 요소 삭제

In [ ]:
# 아이템 : 1이상 10미만의 범위에서 랜덤 정수
# 구조 : 3x5
arr1 = np.random.randint(1,10, (3,5))
np_print(arr1)

In [1]:
import numpy as np

In [17]:
# 아이템 : 1이상 10미만의 범위에서 랜덤 정수
# 구조 : 3x5
arr2 = np.random.randint(1,10, (3,5))
# np_print(arr2)

In [ ]:
# 변경되는 배열의 요소 수가 동일할 경우 : reshape()결과와 동일
# 변경할 구조 : 5x3
arr1.reshape(5,3)

In [ ]:
# resize : 원본 바뀜
arr1.resize((5,3))

In [ ]:
arr1

In [18]:
# 변경되는 배열의 요소 수가 더 많을 경우
# 변경할 구조 : 4x5
arr2

array([[2, 2, 9, 8, 9],
       [5, 4, 6, 2, 3],
       [1, 1, 5, 3, 3]])

In [ ]:
# reshape()
arr2.reshape(4,5)

In [19]:
# np.resize()
np.resize(arr2, (4,5))

array([[2, 2, 9, 8, 9],
       [5, 4, 6, 2, 3],
       [1, 1, 5, 3, 3],
       [2, 2, 9, 8, 9]])

In [20]:
arr2

array([[2, 2, 9, 8, 9],
       [5, 4, 6, 2, 3],
       [1, 1, 5, 3, 3]])

In [23]:
# arr.resize()
# error 확인 
# cannot resize an array that references or is referenced by another array in this way.
# np.resize(arr2, (4,5)) => reference arr2
# arr2.resize((4,5), refcheck=False)
arr2.resize((4,5))

In [24]:
arr2

array([[2, 2, 9, 8, 9],
       [5, 4, 6, 2, 3],
       [1, 1, 5, 3, 3],
       [0, 0, 0, 0, 0]])

In [ ]:
# 변경되는 배열의 요소 수가 더 작을 경우 : 남은 요소 삭제
# 변경할 구조 :3x4
arr2

In [8]:
np.resize(arr2, (3,4))

array([[3, 4, 8, 3],
       [3, 5, 2, 7],
       [1, 8, 2, 6]])

In [7]:
arr2

array([[3, 4, 8, 3],
       [3, 5, 2, 7],
       [1, 8, 2, 6]])

In [9]:
arr2.resize((3,4))

In [5]:
arr2

array([[3, 4, 8, 3],
       [3, 5, 2, 7],
       [1, 8, 2, 6]])

2) 요소 추가
- np.append(arr, values, axis=None)
    - arr 마지막에 values를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 결합
    - axis = 0 : 행 방향으로 결합 (단, 열의 개수가 동일해야 함)
    - axis = 1 : 열 방향으로 결합 (단, 행의 개수가 동일해야 함)
    - 원본 배열들에 반영되지 않음

In [10]:
# 아이템 : 1이상 10미만 차례대로 증가하는 정수
# 구조 : 3x3
a = np.arange(1, 10).reshape(3,3)

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# 아이템 : 10이상 19미만 차례대로 증가하는 정수
# 구조 : 3x3
b = np.arange(10, 19).reshape(3,3)

In [13]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
# 2개의 배열 결합
# axis 지정하지 않는 경우 : 1d 결합
# axis = None
np.append(a, b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [15]:
# 2개의 배열 결합 
# axis = 0 : 행 단위로 결합
np.append(a, b, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [16]:
# 2개의 배열 결합 
# axis = 1 : 열 단위로 결합
np.append(a, b, axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [25]:
# 아이템 : 30 이상 45미만의 정수값, 
# 구조 :3x5
c = np.arange(30, 45).reshape(3,5)
c

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [26]:
# 열의 개수가 다른 배열(a)과의 결합
# a랑 c랑 행 단위로 결합
np.append(a,c, axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
c

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [31]:
# 위의 문제를 해결해보자.
# 행 단위로 결합할 수 있는 구조로 변경 
# 기준 : 열 개수
# 사용할 메서드 : reshape
np.append(a, c.reshape(-1,3), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [36]:
c1 = c.copy()

In [37]:
# c의 구조 변경
# 4행 4열
c1.resize((4,4))

In [38]:
c1

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44,  0]])

In [39]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [42]:
c1.resize((3,4), refcheck=False)

In [43]:
c1

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [44]:
#  행의 개수가 다른 배열(b)과의 결합
np.append(b, c1, axis=1)

array([[10, 11, 12, 30, 31, 32, 33],
       [13, 14, 15, 34, 35, 36, 37],
       [16, 17, 18, 38, 39, 40, 41]])

- np.insert(arr, idx, values, axis=None)
    - 지정한 인덱스(idx)에 value를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열의 변형되고 해당 인덱스에 추가
    - axis = 0 : 행 방향으로 n번째 행에 추가 
    - axis = 1 : 열 방향으로 n번째 열에 추가
    - 원본 배열에 반영되지 않음

In [47]:
# 아이템 : 1 이상 10 미만의 범위에서 1씩 증가하는 숫자
# 구조 : 3x3
x1 = np.arange(1, 10).reshape(3,3)
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
# axis 지정하지 않는 경우 
# 원본객체가 1d array가 됐을 때의 인덱스 번호(1)에 100을 추가
np.insert(x1, 1, 100)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [51]:
# 원본 배열은 변경되지 않음
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# axis = 0 :  행방향 => n번 인덱스 행에 추가
# value가 하나의 값 : 모든 행 요소에 동일한 값 추가
np.insert(x1, 1, 100, axis=0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [53]:
# axis = 1 : 열방향 => n번 인덱스 열에 추가
# value가 하나의 값 : 모든 열 요소에 동일한 값 추가
np.insert(x1, 1, 100, axis=1)

array([[  1, 100,   2,   3],
       [  4, 100,   5,   6],
       [  7, 100,   8,   9]])

In [55]:
# 요소 마다 다른 값으로 행/열을 추가
# 동일한 요소개수(행/열의 요소 개수)를 가지는 리스트로 value 전달
np.insert(x1, 1, [10,20,30], axis=0)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [59]:
np.insert(x1, 1, [10,20,30], axis=1)

array([[ 1, 10,  2,  3],
       [ 4, 20,  5,  6],
       [ 7, 30,  8,  9]])

3) 요소 삭제
- np.delete(arr, idx, axis=None)
    - 지정한 인덱스(idx)에 해당하는 요소를 삭제
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 해당 인덱스에 해당하는 요소를 삭제
    - axis = 0 : 행 방향으로 n번째 행을 삭제
    - axis = 1 : 열 방향으로 n번째 열을 삭제
    - 원본 배열에 반영되지 않음

In [69]:
np.ravel(x1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# axis 지정하지 않는 경우 : 1d 배열로 변환 후 지정한 인덱스의 요소를 삭제
np.delete(x1, 4)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [70]:
# 원본 배열은 변경되지 않음
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
# axis = 0 : 행 삭제
np.delete(x1, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [73]:
# axis = 1 : 열 삭제
np.delete(x1, 0, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

4) 배열 결합
- np.concatenate((arr1, arr2, ...), axis=0)
    - axis = 0(기본값) : 행 방향으로 두 배열 결합 (단, 열의 개수가 동일)
    - axis = 1 : 열 방향으로 두 배열 결합 (단, 행의 개수가 동일)
    - 원본 배열들은 변경되지 않음

In [ ]:
# 4개의 배열 생성
# 1,7 = 2x3
# 7,13 = 2x3
# 13, 23 = 2x5 => 열 개수가 다른 경우
# 23, 38 = 5x3 => 행 개수가 다른 경우

In [74]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
c = np.arange(13,23).reshape(2,5)
d = np.arange(23,38).reshape(5,3)

In [75]:
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[13 14 15 16 17]
 [18 19 20 21 22]]

[[23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]



In [78]:
# 행 방향으로 a,b 배열 결합
# np.append(a,b,axis=0)
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [79]:
# 열 방향으로 a,b 배열 결합
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [80]:
c.shape

(2, 5)

In [82]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# 행 방향으로 결합 조건 : 열 개수 동일
np.concatenate((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [86]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
d

array([[23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [91]:
d

array([[23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [92]:
np.resize(d, (3,4))

array([[23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [107]:
d.resize((2,3))

ValueError: cannot resize this array: it does not own its data

In [94]:
# 열 방향으로 결합 조건 : 행 개수 동일
np.concatenate((a,np.resize(d, (2,4))), axis=1)

array([[ 1,  2,  3, 23, 24, 25, 26],
       [ 4,  5,  6, 27, 28, 29, 30]])

- vstack() 메서드
    - np.vstack((arr1, arr2 ...))
    - 튜플로 전달받은 여러 개의 배열을 행 방향(수직 방향)으로 결합
    - 열의 개수가 동일해야 함
    - np.concatenate((arr1, arr2 ...), axis=0)과 동일한 결과
    - 원본 배열들은 변경되지 않음

In [95]:
# 2행 3열짜리 배열
a

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
# 5행 3열짜리 배열
d

array([[23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [97]:
# 열의 개수가 동일한 두 개의 배열을 행 방향으로 결합
np.vstack((a,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [98]:
# 4개 배열 결합
np.vstack((a,d,a,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [ ]:
# 열의 개수가 다른 배열은 결합할 수 없다.

- np.hstack((arr1, arr2 ...))
    - 튜플로 전달받은 여러 개의 배열을 열 방향(수평 방향)으로 결합
    - 행의 개수가 동일해야 함
    - np.concatenate((arr1, arr2 ...), axis=1)과 동일한 결과

In [99]:
# 행의 개수가 동일한 배열의 열 방향 결합
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [100]:
c

array([[13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22]])

In [101]:
# 4개의 배열 결합
np.hstack((b,c,b,c))

array([[ 7,  8,  9, 13, 14, 15, 16, 17,  7,  8,  9, 13, 14, 15, 16, 17],
       [10, 11, 12, 18, 19, 20, 21, 22, 10, 11, 12, 18, 19, 20, 21, 22]])

- stack() 메서드
    - np.stack((arr1, arr2 ...))
    - 튜플로 전달받은 여러 개의 배열을 3차원으로 결합
    - 행, 열의 구조가 동일해야 함

In [102]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [105]:
np.stack((a,b)).shape

(2, 2, 3)

In [1]:
import numpy as np

5) 배열 분리
- np.vsplit(arr, indices_or_sections)
    - 배열을 행 방향으로 분리하여 각 배열을 리스트로 묶어서 반환
    - 분리할 그룹 개수를 지정 : 균등하게 분리
    - 분리할 기준 인덱스를 리스트로 전달 : 균등하지 않게 분리
    - 원본 배열의 구조(shape)과 비교하여 아이템 개수가 변경
    - 원본 배열은 변경되지 않음

In [2]:
# 아이템 : 1이상 37미만의 범위, 1씩 증가하는 정수
# 구조 : 6x6
a = np.arange(1,37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [6]:
# 결과 배열의 개수를 기준으로 나누기 
# 기준 :  행 방향으로 3개로 나누기
# 반환값 : 부분 배열을 저장하고 있는 리스트
a_split = np.vsplit(a, 3)
type(a_split)

list

In [8]:
# vsplit 반환객체의 하위 아이템은 다시 배열
_split[0].shape

(2, 6)

In [9]:
# 원본 배열은 변경되지 않음
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [10]:
# 간격이 균등하지 않은 경우
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [11]:
# 0
# 1~2
# 3
# 4~5
# section => [1, 3, 4, 6]
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [15]:
# 균등하지 않는 범위에서 행을 기준으로 배열 나누기 
for arr in np.vsplit(a, [1, 3, 4]):
    print(arr)
    print()

[[1 2 3 4 5 6]]

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[19 20 21 22 23 24]]

[[25 26 27 28 29 30]
 [31 32 33 34 35 36]]



- np.hsplit(arr, indices_or_sections)
    - 배열을 열 방향으로 분리하여 각 배열을 리스트로 묶어서 반환
    - 최종적으로 분리할 그룹 개수를 지정하거나 분리할 기준 인덱스를 지정
    - 원본 배열의 구조(shape)과 비교하여 아이템 개수가 변경
    - 원본 배열은 변경되지 않음

In [16]:
# 사용할 배열 확인
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [17]:
# 원본배열을 열 방향으로 6개로 분리 
# 반환값 : 
np.hsplit(a, 6)

[array([[ 1],
        [ 7],
        [13],
        [19],
        [25],
        [31]]), array([[ 2],
        [ 8],
        [14],
        [20],
        [26],
        [32]]), array([[ 3],
        [ 9],
        [15],
        [21],
        [27],
        [33]]), array([[ 4],
        [10],
        [16],
        [22],
        [28],
        [34]]), array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]), array([[ 6],
        [12],
        [18],
        [24],
        [30],
        [36]])]

In [18]:
# 균등하지 않은 기준으로 분리
# section = [2,5] => 1번 인덱스, 4번 인덱스 => 3개
np.hsplit(a, [2,5])

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]]), array([[ 6],
        [12],
        [18],
        [24],
        [30],
        [36]])]

- np.split(arr, indices_or_sections, axis=0)
    - axis = 0(기본값) : 행 단위로 분리
    - axis = 1 : 열 단위로 분리
    - 원본 배열은 변경되지 않음

In [19]:
# 균등하지 않은 간격으로 행 기준으로 분리
# np.split(a, section, axis=0) = np.vsplit(a, section)
np.split(a, [2,5], axis=0)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]), array([[31, 32, 33, 34, 35, 36]])]

In [20]:
np.vsplit(a, [2,5])

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]), array([[31, 32, 33, 34, 35, 36]])]

In [21]:
# 균등한 간격으로 열 기준으로 3개 분리
# np.split(a, k, axis=1) = np.hsplit(a, k)
np.split(a, 3, axis=1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]), array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]), array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]

In [22]:
np.hsplit(a, 3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]), array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]), array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]